from flask import Flask, request, jsonify
import os
import requests
import time
import re
from web3 import Web3
import json

app = Flask(__name__)

# Config - Vercel environment variables
ELEVENLABS_API_KEY = os.getenv("ELEVENLABS_API_KEY")
AIML_API_KEY = os.getenv("AIML_API_KEY")

# Tera Wallet
CREATOR_ADDRESS = "0x2de592b3951807dfb72931596d11fe93b753881e"

# Arc Testnet
w3 = Web3(Web3.HTTPProvider("https://rpc.testnet.arc.network"))

# USDC Contract
USDC_ADDRESS = "0x3600000000000000000000000000000000000000"
USDC_DECIMALS = 6

# In-memory storage
user_sessions = {}

print("🎭 AI Story Teller Server Started on Vercel!")

# AI & TTS Functions
def generate_story_with_ai(prompt):
    """Generate engaging story with AI"""
    try:
        # For testing - return simple story
        return f"Once upon a time, there was a magical {prompt}. This story was generated by AI. The full version will have more details and audio narration."
    except Exception as e:
        print(f"AI Generation Error: {e}")
        return "In a hidden valley where moonlight danced on silver streams, lived a young fox named Ember who could understand the whispers of the wind."

def create_teaser(full_story):
    """Create teaser from full story"""
    teaser = full_story[:150] + "..."
    teaser += " 🎧 Tip $0.50 to unlock the full magical story!"
    return teaser

def text_to_speech(text, filename):
    """Convert text to speech - Vercel compatible"""
    if not ELEVENLABS_API_KEY:
        print("ElevenLabs API key not configured")
        return None
    return None  # Temporary disable audio

# Payment Functions
def build_tip_tx(user_address):
    """Build transaction for USDC tip"""
    try:
        return {"status": "test_tx"}, "ready"
    except Exception as e:
        return None, str(e)

# Routes
@app.route('/connect', methods=['POST'])
def connect():
    try:
        data = request.get_json()
        user_wallet = data.get('wallet')
        if user_wallet and w3.is_address(user_wallet):
            user_sessions[user_wallet] = {"full_story": ""}
            return jsonify({"status": "connected", "wallet": user_wallet})
        return jsonify({"status": "failed"}), 400
    except Exception as e:
        return jsonify({"error": str(e)}), 500

@app.route('/chat', methods=['POST'])
def chat():
    try:
        data = request.get_json()
        if not data:
            return jsonify({"reply": "No data received"}), 400
            
        user_message = data.get('message', '').strip().lower()
        user_wallet = data.get('wallet')
        
        print(f"📖 Received: {user_message} from {user_wallet}")
        
        if not user_message:
            return jsonify({"reply": "Please enter a story topic!"})
        
        if not user_wallet:
            return jsonify({"reply": "Please connect your wallet first!"})
        
        # Generate story
        full_story = generate_story_with_ai(user_message)
        teaser = create_teaser(full_story)
        
        # Store in session
        user_sessions[user_wallet] = {"full_story": full_story}
        
        return jsonify({
            "reply": "✨ Your story teaser is ready!",
            "written": teaser,
            "canTip": True
        })
        
    except Exception as e:
        print(f"❌ Chat error: {e}")
        return jsonify({"reply": f"Server error: {str(e)}"}), 500

@app.route('/tip', methods=['POST'])
def tip():
    try:
        data = request.get_json()
        user_wallet = data.get('wallet')
        
        if not user_wallet:
            return jsonify({"reply": "Connect wallet first!"})
        
        tx, status = build_tip_tx(user_wallet)
        if tx:
            return jsonify({
                "reply": "Confirm in MetaMask to pay $0.50!",
                "tx": tx,
                "status": "sign_required"
            })
        else:
            return jsonify({"reply": f"Tip failed: {status}"})
    except Exception as e:
        return jsonify({"reply": f"Error: {str(e)}"}), 500

@app.route('/confirm_tx', methods=['POST'])
def confirm_tx():
    try:
        data = request.get_json()
        tx_hash = data.get('tx_hash')
        user_wallet = data.get('wallet')
        
        if not tx_hash or not user_wallet:
            return jsonify({"error": "No tx hash or wallet"}), 400

        full_story = user_sessions.get(user_wallet, {}).get("full_story", "")
        
        if not full_story:
            return jsonify({"error": "No story found"}), 400

        return jsonify({
            "reply": "Tip received! Full story unlocked!",
            "written": full_story,
            "explorer": f"https://testnet.arcscan.app/tx/{tx_hash}"
        })
    except Exception as e:
        return jsonify({"error": str(e)}), 500

# Vercel serverless handler - FIXED VERSION
def handler(request, context):
    try:
        with app.app_context():
            return app(request, context)
    except Exception as e:
        return {
            'statusCode': 500,
            'headers': {'Content-Type': 'application/json'},
            'body': json.dumps({'error': str(e), 'message': 'Server error occurred'})
        }

# For local development
if __name__ == '__main__':
    app.run(debug=True)